protected/controllers/EditorController.php
<?php

class EditorController extends Controller
{
	function init()
	{
		

		Yii::app()->user->setState('mobile', false);
		$this->layout='main';
		Yii::app()->language = "es";
		parent::init();
	
	}
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}
	public function accessRules()
	{
		//die(var_dump(Yii::app()->user->checkAccess("admin")))  ;
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('installdb', 'upgrade'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','forms', 'subforms', 'cloudinator'),
				'roles'=>array("admin"),
			),	
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actionForms()
	{
		$formvisibles =new CActiveDataProvider('Forms', array(
				'criteria'=>array(
					'condition' => "visible=1 AND deleted = 0",
			),
			));
		$formnovisibles = new CActiveDataProvider('Forms', array(
				'criteria'=>array(
					'condition' => "visible=0 AND deleted = 0",
			),
			));
		$this->render('forms',array(
			'formvisibles'=>$formvisibles,
			'formnovisibles'=>$formnovisibles,
		));
		
	}

	public function actionIndex()
	{
		$this->redirect(array('forms'));
	}
	
	public function actionCloudinator($id)
	{
		$subformulario = Subforms::model()->find("id = $id");
		$this->renderPartial('cloudinator',array(
			'subformulario'=>$subformulario,
		));
	}

	public function actionSubforms($id)
	{
		$formulario = Forms::model()->find("id = $id");
		$subformpublicados =new CActiveDataProvider('Subforms', array(
				'criteria'=>array(
					'condition' => "released=1 AND megatree = $formulario->id AND deleted = 0",
			),
			));
		$subformnopublicados = new CActiveDataProvider('Subforms', array(
				'criteria'=>array(
					'condition' => "released=0 AND megatree = $formulario->id AND deleted = 0",
			),
			));
		$this->render('subforms',array(
			'formulario' => $formulario,
			'subformpublicados'=>$subformpublicados,
			'subformnopublicados'=>$subformnopublicados,
		));
	}
	public function actionUpgrade()
	{
		$this->renderPartial('upgrade');
	}
	
	public function actionInstallDB()
	{
		$this->renderPartial('installdb');
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}*/

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

}

protected/controllers/FormsController.php
<?php

class FormsController extends Controller
{
	
	function init()
	{
		parent::init();
	
		Yii::app()->language = "es";
		Yii::app()->user->setState('mobile', false);
		$this->layout='main';
	}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(

			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','view', 'admin','delete', 'create','update', 'setvisible', 'setnovisible'),
				'roles'=>array("admin"),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Forms;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Forms']))
		{
			$model->attributes=$_POST['Forms'];
			$model->deleted = 0;
			$model->created = date("Y-m-d H:i:s");
			if($model->save())
				$this->redirect(array('editor/index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Forms']))
		{
			$model->attributes=$_POST['Forms'];
			if($model->save())
				$this->redirect(array('editor/index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$form= $this->loadModel($id);
		Yii::app()->db->createCommand("UPDATE trees SET deleted = 1 WHERE megatree = $form->id")->execute();
		
		$form->attributes = array("deleted"=>1);
		
		if($form->save())
				$this->redirect(array('editor/forms'));
		
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Forms');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	
	public function actionSetVisible($id){
		$model = $this->loadModel($id);
		$model->attributes= array('visible'=>1);
			if($model->save())
				$this->redirect(array('editor/index'));
		
	}
	public function actionSetNoVisible($id){
		$model = $this->loadModel($id);
		$model->attributes= array('visible'=>0);
			if($model->save())
				$this->redirect(array('editor/index'));
		
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Forms('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Forms']))
			$model->attributes=$_GET['Forms'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Forms the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Forms::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Forms $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='forms-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SubformsController.php
<?php

class SubformsController extends Controller
{
	function init()
	{
		parent::init();
	
		Yii::app()->language = "es";
		Yii::app()->user->setState('mobile', false);
		$this->layout='main';
	}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','view', 'create','update', 'admin','delete', 'release', 'clone'),
				'roles'=>array("admin"),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actionClone($id){
		
		$model = new Subforms();
		$modeltoclone = $this->loadModel($id);
		Yii::app()->user->returnUrl = $this->createUrl('editor/subforms', array('id'=>$modeltoclone->megatree));
		if(isset($_POST['Subforms']))
		{
			$model->attributes=$_POST['Subforms'];
			$model->megatree = $modeltoclone->megatree;
			$model->created = date("Y-m-d H:i:s");
			$model->modified = date("Y-m-d H:i:s");
			$convert = array();
			if($model->save()){
				$nodos = Nodos::model()->findAll("tree = $modeltoclone->id");
				foreach ($nodos as $nodo){
					$nodonuevo = new Nodos();
					$nodonuevo->attributes = array("tree"=>$model->id, 
													"name"=>$nodo->name, 
													"type"=>$nodo->type, 
													"posx"=>$nodo->posx, 
													"posy"=>$nodo->posy, 
													"metaname"=>$nodo->metaname, 
													"metadata"=>$nodo->metadata, 
													"metatype"=>$nodo->metatype, 
													"modified"=>date("Y-m-d H:i:s"),
													);
					$nodonuevo->save();
					$convert[$nodo->id] =(int)$nodonuevo->id;
				}
				//die(var_dump($convert));
				$links = Links::model()->findAll("tree = $modeltoclone->id");
				$debug = array();
				foreach ($links as $link){
					
					if(isset($convert[$link->target]) && isset($convert[$link->source]) ){
						$target = Nodos::model()->find("id = ".$convert[$link->target]);
						$source = Nodos::model()->find("id = ".$convert[$link->source]);
					
						$linknuevo = new Links();
						$linknuevo->attributes = array("tree"=>$model->id, 
													"name"=>$link->name, 
													"source"=>$source->id, 
													"target"=>$target->id, 
													"modified"=>date("Y-m-d H:i:s"),
													);
						$linknuevo->save();
					}
				}
				
				$this->redirect(array('editor/subforms','id'=>$model->megatree));
			}
		}
		
		$this->render('clone', array(
					'model'=>$model,
					'modeltoclone'=>$modeltoclone,
					));
		
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($id)
	{
		
		$model=new Subforms;
		$form = Forms::model()->find("id=$id");
		Yii::app()->user->returnUrl = $this->createUrl('editor/subforms', array('id'=>$form->id));

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subforms']))
		{
			$model->attributes=$_POST['Subforms'];
			$model->megatree = $form->id;
			$model->created = date("Y-m-d H:i:s");
			$model->modified = date("Y-m-d H:i:s");
			if($model->save())
				$this->redirect(array('editor/subforms','id'=>$model->megatree));
		}

		$this->render('create',array(
			'model'=>$model,
			'form'=>$form,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		Yii::app()->user->returnUrl = $this->createUrl('editor/subforms', array('id'=>$model->megatree));
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subforms']))
		{
			$model->attributes=$_POST['Subforms'];
			$model->modified = date("Y-m-d H:i:s");
			if($model->save())
				$this->redirect(array('editor/subforms','id'=>$model->megatree));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model = $this->loadModel($id);
		
		$model->attributes = array('deleted'=>1);
		
		if($model->save())
			$this->redirect(array('editor/subforms','id'=>$model->megatree));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Subforms');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	
	public function actionRelease($id)
	{
		$model = $this->loadModel($id);
		$model->attributes= array('released'=>1);
			if($model->save())
				$this->redirect(array('editor/subforms', 'id'=>$model->megatree));
	}
	



	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Subforms the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Subforms::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Subforms $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='subforms-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/editor/forms.php
<?php
/* @var $this EditorController */
/*'formvisibles'=>$formvisibles,
 'formnovisibles'=>$formnovisibles,*/

$this->breadcrumbs=array(
	'Propuestas Tipo',
);
?>
<br/>
<?php /*
(*) Notas:<br/>
-Las Propuesta Tipo sirven para hacer agrupaciones de productos.<br/>
-Las Propuesta Tipo Ocultas no serán visibles en la interfaz de ejecutor.<br/>
*/?>

<form style="text-align: right; vertical-align: top;" action="<?php echo Yii::app()->request->baseUrl."/forms/create";?>" data-ajax="false">
	<div class="row buttons">
	<?php echo CHtml::submitButton("Nueva Propuesta Tipo"); ?>
	</div>
</form>
<div style ="float:left;width:47%;">
<h3>Propuestas Tipo Visibles</h3>

<?php $this->widget('zii.widgets.grid.CGridView', array(
							'dataProvider'=>$formvisibles,
							'htmlOptions' => array("data-ajax"=>"false"),
							'columns'=>array(
								array(
						            'name'=>'name',
								 	'type'=>'raw',
						            'value'=>'CHtml::link("$data->name",array("editor/subforms",
                                         "id"=>"$data->id"))',
						        ),
								'created',
								array(
									'class'=>'CButtonColumn',
									'template'=>'{update} {visible} {delete}  ',
											'buttons' => array(
													'update'=>array(
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("forms/update", array("id"=>$data->id))',
															),
													'visible'=>array(
															'label' => 'Dejar Oculto',
															'htmlOptions' => array("data-ajax"=>"false"),
															'imageUrl' => Yii::app()->baseUrl.'/images/novisible.jpg',
															'url'=>'Yii::app()->createUrl("forms/setnovisible", array("id"=>$data->id))',
															),
													'delete'=>array(
															'label' => 'Eliminar',
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("forms/delete", array("id"=>$data->id))',
															),
											),
								),
								),
								));?>
</div>
								
<div style ="float:right;width:47%;">
<h3>Propuestas Tipo Ocultas</h3>						
<?php $this->widget('zii.widgets.grid.CGridView', array(
							'dataProvider'=>$formnovisibles,
							'htmlOptions' => array("data-ajax"=>"false"),
							
							'columns'=>array(
								 array(
						            'name'=>'name',
								 	'type'=>'raw',
						            'value'=>'CHtml::link("$data->name",array("editor/subforms",
                                         "id"=>"$data->id"))',
						        ),
						        'created',
								
								array(
									'class'=>'CButtonColumn',
									'template'=>'{update} {novisible} {delete}  ',
											'buttons' => array(
													'update'=>array(
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("forms/update", array("id"=>$data->id))',
															),
													'novisible'=>array(
															'label' => 'Dejar Visible',
															'htmlOptions' => array("data-ajax"=>"false"),
															'imageUrl' => Yii::app()->baseUrl.'/images/visible.jpg',
															'url'=>'Yii::app()->createUrl("forms/setvisible", array("id"=>$data->id))',
															),
													'delete'=>array(
															'label' => 'Eliminar',
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("forms/delete", array("id"=>$data->id))',
															),
											),
								),
								),
								));?>
								
								</div>

						
								
								

protected/views/editor/installdb.php
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Cloudinator - Instalación</title>
</head>
<body>
<?php
$config = parse_ini_file(Yii::app()->basePath."/config/config.ini" , true);
$connconf = $config["mysql"];

echo '<a href="../editor.php">Volver</a>';
echo '<center><br><h2>Instalacion de la base de datos</h2><br>';

echo '<hr>';
//crear tabla "nodos"
echo '<h3>Creando Tabla "nodos"</h3>';
try {
	Yii::app()->db->createCommand("CREATE TABLE nodos (
		id int(100) not null auto_increment primary key,
		tree int(50) NOT NULL,
		name varchar(50) NOT NULL,
		type varchar(25) NOT NULL,
		posx float(50) NOT NULL,
		posy float(50) NOT NULL,
		metaname varchar(50),
		metadata varchar(400),
		metatype varchar(25),
		modified timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	")->execute();
	echo 'Tabla "nodos" creada exitosamente';
} catch (Exception $e) {
	echo 'Error al crear tabla "nodos"<br>';
	echo $e;
}
echo '<hr>';
//crear tabla "links" id, name, source, target
echo '<h3>Creando Tabla "links"</h3>';
try {
	Yii::app()->db->createCommand("CREATE TABLE links (
		id int(100) not null auto_increment primary key,
		tree int(50) NOT NULL,
		name varchar(50),
		source varchar(50),
		target varchar(50),
		modified timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	")->execute();
	echo 'Tabla "links" creada exitosamente';
} catch (Exception $e) {
	echo 'Error al crear tabla "links"<br>';
	echo $e;
}
echo '<hr>';
//crear tabla "trees" id, name, source, target
echo '<h3>Creando Tabla "trees"</h3>';
try {
	Yii::app()->db->createCommand("CREATE TABLE IF NOT EXISTS `trees` (
		`id` int(100) NOT NULL AUTO_INCREMENT ,
		`name` varchar(50) NOT NULL,
		`megatree` int(100) NOT NULL,
		`deleted` tinyint(1) NOT NULL,
		`created` datetime NOT NULL,
		`modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	")->execute();
	echo 'Tabla "trees" creada exitosamente';
} catch (Exception $e) {
	echo 'Error al crear tabla "trees"<br>';
	echo $e;
}
echo '<hr>';
//crear tabla "megatrees" id, name, source, target
echo '<h3>Creando Tabla "megatrees"</h3>';
try {
	Yii::app()->db->createCommand("CREATE TABLE IF NOT EXISTS `megatrees` (
		`id` int(100) NOT NULL AUTO_INCREMENT,
		`name` varchar(50) NOT NULL,
		`chain` varchar(1000),
		`deleted` tinyint(1) NOT NULL,
		`created` datetime NOT NULL,
		`modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	")->execute();
	echo 'Tabla "megatrees" creada exitosamente';
} catch (Exception $e) {
	echo 'Error al crear tabla "megatrees"<br>';
	echo $e;
}
echo '<hr>';
//crear tabla "users"
echo '<h3>Creando Tabla "users"</h3>';
try {
	Yii::app()->db->createCommand("CREATE TABLE IF NOT EXISTS `users` (
		`id` int(100) NOT NULL AUTO_INCREMENT,
		`email` varchar(50) NOT NULL,
		`name` varchar(50),
		`lastname` varchar(50),
		`password` varchar(50),
		`firstaccess` datetime NOT NULL,
		`lastaccess` datetime NOT NULL,
		`lang` varchar(50),
		`modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	")->execute();
	echo 'Tabla "users" creada exitosamente';
} catch (Exception $e) {
	echo 'Error al crear tabla "users"<br>';
	echo $e;
}
echo '<hr>';
//Crear tabla "empresas"
echo '<h3>Creando Tabla "empresas"</h3>';
try {
	Yii::app()->db->createCommand("CREATE TABLE IF NOT EXISTS `empresas` (
		`id` int(100) NOT NULL AUTO_INCREMENT,
		`nombre` varchar(50) NOT NULL,
		`industria` varchar(50),
		`contactado` varchar(50),
		`areacontacto` varchar(50),
		`infolevantamiento` varchar(5000),
		`modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
	")->execute();
	echo 'Tabla "empresas" creada exitosamente';
} catch (Exception $e) {
	echo 'Error al crear tabla "empresas"<br>';
	echo $e;
}
echo '<hr>';
echo '<h3>La instalacion a finalizado</h3>';
echo '<h2>Si la instalación fue exitosa, por favor instale las actualizaciones: <a href="upgrade">Instalar Actualizaciones</a></h2>';
echo '</center>';


echo '<a href="editor">Volver</a>';
?>
</body>

protected/views/editor/subforms.php
<?php
/* @var $this EditorController */
/*'subformpublicados'=>$subformpublicados,
 'subformnopublicados'=>$subformnopublicados,
 $formulario
 */

$this->breadcrumbs=array(
	'Propuestas Tipo'=>array('/editor'),
	'Productos de '.$formulario->name,
);
?>
<h2><?php echo "Propuesta Tipo: ".$formulario->name; ?></h2>
<p>(*) Los Productos publicados no se pueden editar </p>
<form style="text-align: right; vertical-align: top;" action="<?php echo Yii::app()->request->baseUrl."/subforms/create/id/".$formulario->id;?>" data-ajax="false">
	<div class="row buttons">
	<?php echo CHtml::submitButton("Nuevo Producto"); ?>
	</div>
</form>

<div style ="float:left;width:45%;">
<h2>Productos publicados</h2>
<?php $this->widget('zii.widgets.grid.CGridView', array(
							'dataProvider'=>$subformpublicados,
							'htmlOptions' => array("data-ajax"=>"false"),
							'columns'=>array(
								array(
						            'name'=>'name',
								 	'type'=>'raw',
						            'value'=>'CHtml::link("$data->name",array("editor/cloudinator",
                                         "id"=>"$data->id"))',
						        ),
								'created',
								array(
									'class'=>'CButtonColumn',
									'template'=>'{update} {clone} {delete}  ',
											'buttons' => array(
													'update'=>array(
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("subforms/update", array("id"=>$data->id))',
															),
													'clone'=>array(
															'label' => 'Clonar',
															'htmlOptions' => array("data-ajax"=>"false"),
															'imageUrl' => Yii::app()->baseUrl.'/images/clone.jpg',
															'url'=>'Yii::app()->createUrl("subforms/clone", array("id"=>$data->id))',
															),
													'delete'=>array(
															'label' => 'Eliminar',
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("subforms/delete", array("id"=>$data->id))',
															),
											),
								),
								),
								));?>
								
</div>

<div style ="float:right;width:45%;">
<h2>Productos no publicados</h2>
<?php $this->widget('zii.widgets.grid.CGridView', array(
							'dataProvider'=>$subformnopublicados,
							'htmlOptions' => array("data-ajax"=>"false"),
							'columns'=>array(
								array(
						            'name'=>'name',
								 	'type'=>'raw',
						            'value'=>'CHtml::link("$data->name",array("editor/cloudinator",
                                         "id"=>"$data->id"))',
						        ),
								'created',
								array(
									'class'=>'CButtonColumn',
									'template'=>'{publicar} {update} {clone} {delete}  ',
											'buttons' => array(
													'publicar'=>array(
															'htmlOptions' => array("data-ajax"=>"false"),
															'imageUrl' => Yii::app()->baseUrl.'/images/publish.gif',
															'url'=>'Yii::app()->createUrl("subforms/release", array("id"=>$data->id))',
															),
													'update'=>array(
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("subforms/update", array("id"=>$data->id))',
															),
													'clone'=>array(
															'label' => 'Clonar',
															'htmlOptions' => array("data-ajax"=>"false"),
															'imageUrl' => Yii::app()->baseUrl.'/images/clone.jpg',
															'url'=>'Yii::app()->createUrl("subforms/clone", array("id"=>$data->id))',
															),
													'delete'=>array(
															'label' => 'Eliminar',
															'htmlOptions' => array("data-ajax"=>"false"),
															'url'=>'Yii::app()->createUrl("subforms/delete", array("id"=>$data->id))',
															),
											),
								),
								),
								));?>
</div>