protected/controllers/EditorController.php
<?php

class EditorController extends Controller
{
	function init()
	{
		

		Yii::app()->user->setState('mobile', false);
		$this->layout='main';
		Yii::app()->language = "es";
		parent::init();
	
	}
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}
	public function accessRules()
	{
		//die(var_dump(Yii::app()->user->checkAccess("admin")))  ;
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('installdb', 'upgrade'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','forms', 'subforms', 'cloudinator'),
				'roles'=>array("admin"),
			),	
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	public function actionForms()
	{
		$formvisibles =new CActiveDataProvider('Forms', array(
				'criteria'=>array(
					'condition' => "visible=1 AND deleted = 0",
			),
			));
		$formnovisibles = new CActiveDataProvider('Forms', array(
				'criteria'=>array(
					'condition' => "visible=0 AND deleted = 0",
			),
			));
		$this->render('forms',array(
			'formvisibles'=>$formvisibles,
			'formnovisibles'=>$formnovisibles,
		));
		
	}

	public function actionIndex()
	{
		$this->redirect(array('forms'));
	}
	
	public function actionCloudinator($id)
	{
		$subformulario = Subforms::model()->find("id = $id");
		$this->renderPartial('cloudinator',array(
			'subformulario'=>$subformulario,
		));
	}

	public function actionSubforms($id)
	{
		$formulario = Forms::model()->find("id = $id");
		$subformpublicados =new CActiveDataProvider('Subforms', array(
				'criteria'=>array(
					'condition' => "released=1 AND megatree = $formulario->id AND deleted = 0",
			),
			));
		$subformnopublicados = new CActiveDataProvider('Subforms', array(
				'criteria'=>array(
					'condition' => "released=0 AND megatree = $formulario->id AND deleted = 0",
			),
			));
		$this->render('subforms',array(
			'formulario' => $formulario,
			'subformpublicados'=>$subformpublicados,
			'subformnopublicados'=>$subformnopublicados,
		));
	}
	public function actionUpgrade()
	{
		$this->renderPartial('upgrade');
	}
	
	public function actionInstallDB()
	{
		$this->renderPartial('installdb');
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}*/

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

}

protected/controllers/FormsController.php
<?php

class FormsController extends Controller
{
	
	function init()
	{
		parent::init();
	
		Yii::app()->language = "es";
		Yii::app()->user->setState('mobile', false);
		$this->layout='main';
	}
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(

			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','view', 'admin','delete', 'create','update', 'setvisible', 'setnovisible'),
				'roles'=>array("admin"),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Forms;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Forms']))
		{
			$model->attributes=$_POST['Forms'];
			$model->deleted = 0;
			$model->created = date("Y-m-d H:i:s");
			if($model->save())
				$this->redirect(array('editor/index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Forms']))
		{
			$model->attributes=$_POST['Forms'];
			if($model->save())
				$this->redirect(array('editor/index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$form= $this->loadModel($id);
		Yii::app()->db->createCommand("UPDATE trees SET deleted = 1 WHERE megatree = $form->id")->execute();
		
		$form->attributes = array("deleted"=>1);
		
		if($form->save())
				$this->redirect(array('editor/forms'));
		
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Forms');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	
	public function actionSetVisible($id){
		$model = $this->loadModel($id);
		$model->attributes= array('visible'=>1);
			if($model->save())
				$this->redirect(array('editor/index'));
		
	}
	public function actionSetNoVisible($id){
		$model = $this->loadModel($id);
		$model->attributes= array('visible'=>0);
			if($model->save())
				$this->redirect(array('editor/index'));
		
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Forms('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Forms']))
			$model->attributes=$_GET['Forms'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Forms the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Forms::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Forms $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='forms-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
<?php echo $content; ?>
</div>
<!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
	<?php echo $content; ?>
	</div>
	<!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
	$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
	));
	$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
	));
	$this->endWidget();
	?>
	</div>
	<!-- sidebar -->
</div>
	<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
	<style type="text/css" media="screen">
		body{
			display: block;
			margin: 0px;
		}
		h1 {
			color: black;
		}
		#newTreeName{
			display: none;
			position: absolute;
			top: 40%;
			left: 35%;
			height: 100px;
			width: 300px;
			text-align: center;
			z-index: 90002;
			background-color: #FFFFFF;
			border: 5px groove #9090dd;
		}
		#newFormName{
			display: none;
			position: absolute;
			top: 40%;
			left: 35%;
			height: 100px;
			width: 300px;
			text-align: center;
			z-index: 90002;
			background-color: #FFFFFF;
			border: 5px groove #9090dd;
		}
		#copyTreeName{
			display: none;
			position: absolute;
			top: 40%;
			left: 35%;
			height: 100px;
			width: 300px;
			text-align: center;
			z-index: 90002;
			background-color: #FFFFFF;
			border: 5px groove #9090dd;
		}
		#cloneFormName{
			display: none;
			position: absolute;
			top: 40%;
			left: 35%;
			height: 130px;
			width: 300px;
			text-align: center;
			z-index: 90002;
			background-color: #FFFFFF;
			border: 5px groove #9090dd;
		}
		#notices{
			position: fixed;
			top: 0;
			left: 40%;
			width: 20%;
			text-align: center;
			z-index: 90007;
			cursor: pointer;
		}
		.menu_subformularios{
			display: none;
		}
		.menu_formularios{
			display: none;
		}
		.tabla{
			left: 20px;
			right: 20px;
			top: 10px;
		}
		.formElement{
			margin: 5px;
		}
		.formPopUp{
			height: auto;
		}
		.header{
			background-image: url("http://www.sonda.com/media/media2011/img/fondo-new.jpg");
			background-repeat: repeat-x;
			height: auto;
			min-height: 90px;
			width: 100%;
		}
		.bg_top {
			background: url("http://www.sonda.com/media/media2011/img/fondo-header.jpg") repeat-x scroll 0;
			width: 100%;
			height: auto;
			position: relative;
			right: 0;
			top: 0;
			overflow: hidden;
			min-width: 1024px;
		}
		.backWhite{
			background-color: #FFFFFF;
		}
		.loading{
			position: fixed;
			display: none;
			top: 45%;
		    left: 45%;
		    z-index: 90008;
		}
		.blackout{
			background-color: #DDDDDD;
			position: fixed;
			top: 0;
			left: 0;
			height: 100%;
			width: 100%;
			opacity: 0.5;
			z-index: 90001;
		}
	</style>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo">
		<?php $imghtml= CHtml::image(Yii::app()->request->baseUrl.'/images/logosonda.jpg', 'DORE'); ?>
		<?php echo CHtml::link($imghtml, array('editor/forms'));?>
		</div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				/*array('label'=>'Nuevo Formulario', 'url'=>array('forms/create'), 'visible'=>!Yii::app()->user->isGuest),*/
				array('label'=>'Volver a Modo Ejecutor', 'url'=>array('site/index'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Actualizaciones', 'url'=>array('/editor/upgrade'), 'visible'=>!Yii::app()->user->isGuest),
				//array('label'=>'Contact', 'url'=>array('/site/contact'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Cerrar Sesión ('.Yii::app()->user->name.' '.Yii::app()->user->lastname.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'homeLink'=>CHtml::link('Administración', array('/editor/forms')),
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; 2014 by Cloudlab UAI.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/layouts/mobile.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
	
	<!-- blueprint CSS framework> 
		<!--end css-->
	<!--[if lt IE 8]>
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
		<![endif]-->
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
		<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	
	<!-- jquery mobile -->
	<link rel="stylesheet"
		href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script
		src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
	
	
	<link rel="stylesheet" type="text/css"
		href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
		<link rel="stylesheet" type="text/css"
		href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	
	<style type="text/css" media="screen">
		.container {
			padding-right: 20%;
			padding-left: 20%;
		},
		a {
			rel: external
		}
	</style>
	<?php Yii::app()->clientScript->registerCoreScript('jquery');?>
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
		<div data-role="header" data-theme="b">
			<h1>
			<?php echo $this->pageTitle; ?>
			</h1>

			<?php if(Yii::app()->user->isGuest){?>
				<a id="popup" href="#popupNested" data-rel="popup" data-role="button"
					data-inline="true" data-icon="bars" data-theme="b"
					data-transition="pop"><?php echo Yii::t('contentForm', 'language')?>
				</a>
			<?php }else{?>
				<a href="<?php echo Yii::app()->user->returnUrl; ?>" rel="external" data-icon="arrow-l"><?php echo Yii::t('contentForm', 'back')?> </a>
				<a href="#right-panel" data-icon="bars" data-iconpos="notext" data-shadow="false" data-iconshadow="false"><?php echo Yii::t('contentForm', 'options');?>
				</a>
			<?php }?>
			
		</div>
		

		<div data-role="popup" id="popupNested" data-theme="none">
			<fieldset data-role="controlgroup">
				<input name="radio-choice-1" id="es" value="es" <?php if(Yii::app()->language=="es"){echo "checked=checked";} ?> type="radio" />
				<label id="toes" for="es">Español</label> 
				<input name="radio-choice-1" id="pt" value="pt" <?php if(Yii::app()->language=="pt"){echo "checked=checked";} ?> type="radio" /> 
				<label id="topt"  for="pt">Portugués</label> 
				<input name="radio-choice-1" id="en" value="en" <?php if(Yii::app()->language=="en"){echo "checked=checked";} ?> type="radio" /> 
				<label id="toen"  for="en">English</label>
			</fieldset>
		</div>
		<!-- /popup -->


		<div id="page" data-role="content">
		<?php if(isset($this->breadcrumbs)){?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
				'homeLink'=>CHtml::link('Seleccionar Empresa', array('/site/selectcompany')),
				'links'=>$this->breadcrumbs,
				'htmlOptions' => array("data-ajax"=>"false"),
		)); ?>
			<!-- breadcrumbs -->
		<?php }?>
		
			<div data-role="panel" data-display='overlay' data-position='right' id="right-panel" data-theme="c">
		        <ul data-role="listview" data-theme="d">
		            <li data-icon="delete"><a href="#" data-rel="close"><?php echo Yii::t('contentForm', 'close')?></a></li>
		            <li data-role="list-divider"><?php echo Yii::t('contentForm', 'options');?></li>
		            <?php if(Yii::app()->user->getState('roles')=="admin"){?>
						<li><a href="<?php echo Yii::app()->request->baseUrl.'/editor'; ?>" rel="external" data-icon="arrow-l">Administración</a></li>
					<?php }?>
		            <li><a href='<?php echo Yii::app()->request->baseUrl;?>/users'  rel="external"
						class='usuarios'><?php echo Yii::t('contentForm', 'managingusers')?></a>
					</li>
					<?php if(Yii::app()->user->getState('roles')=="admin"){?>
						<li><a href='<?php echo Yii::app()->request->baseUrl;?>/companies' rel="external"><?php echo Yii::t('contentForm', 'managingcompanies')?>  
						</a></li>
					<?php }?>
					
			        <li><a href='<?php echo Yii::app()->request->baseUrl;?>/site/logout' rel="external"
					class='cerrarsesion'><?php echo Yii::t('contentForm', 'logout')?> </a></li>

		        </ul>
		        <div data-role="collapsible" data-inset="false" data-iconpos="right" data-theme="d" data-content-theme="d">
		        
		        </div><!-- /collapsible -->
		    </div><!-- /panel -->

			<?php echo $content; ?>

			<div class="clear"></div>

			<div id="footer">
				Copyright &copy;
				<?php echo 2014; ?>
				Cloudlab UAI<br /> All Rights Reserved.<br />
				<?php echo Yii::powered(); ?>
			</div>
			<!-- footer -->

		</div>

<script type="text/javascript">

$( document ).ready(function() {
	$('.ui-link').each(function(){
		$(this).attr('rel', 'external');
	});
	$('.sort-link').each(function(){
		$(this).css('color', 'white');
	});
	$('#toes').on('click',function(){
		window.location.href = "login?lang=es";
	});
	$('#toen').on('click', function(){
		window.location.href = "login?lang=en";
	});
	$('#topt').on('click', function(){
		window.location.href = "login?lang=pt";
	});
});


</script>
		

</body>

</html>