protected/models/Levantamientos.php
<?php

/**
 * This is the model class for table "levantamientos".
 *
 * The followings are the available columns in table 'levantamientos':
 * @property integer $id
 * @property string $titulo
 * @property integer $empresaid
 * @property string $info
 * @property string $formsactivos
 * @property string $conctadopor
 * @property string $areacontacto
 * @property string $completitud
 * @property string $created
 * @property string $modified
 * @property integer $deleted
 */
class Levantamientos extends CActiveRecord
{
	public $forms;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'levantamientos';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
		array('titulo',  'required'),
		array('empresaid, deleted', 'numerical', 'integerOnly'=>true),
		array('titulo, formsactivos', 'length', 'max'=>150),
		array('info', 'length', 'max'=>500),
		array('conctadopor, areacontacto, completitud', 'length', 'max'=>100),
		array('created, modified', 'safe'), 
		// The following rule is used by search().
		// @todo Please remove those attributes that should not be searched.
		array('id, titulo, empresaid, info, formsactivos, conctadopor, areacontacto, completitud, created, modified, deleted', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'titulo' => Yii::t('contentForm', 'titlevisit'),
			'empresaid' => 'Empresaid',
			'info' => Yii::t('contentForm', 'info'),
			'formsactivos' => 'Formsactivos',
			'conctadopor' => Yii::t('contentForm', 'contactedby'),
			'areacontacto' => Yii::t('contentForm', 'contactedarea'),
			'completitud' => 'Completitud',
			'created' => 'Created',
			'modified' => Yii::t('contentForm', 'lastmod'),
			'deleted' => 'Deleted',

			'forms' => Yii::t('contentForm', 'forms'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('titulo',$this->titulo,true);
		$criteria->compare('empresaid',$this->empresaid);
		$criteria->compare('info',$this->info,true);
		$criteria->compare('formsactivos',$this->formsactivos,true);
		$criteria->compare('conctadopor',$this->conctadopor,true);
		$criteria->compare('areacontacto',$this->areacontacto,true);
		$criteria->compare('completitud',$this->completitud,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('modified',$this->modified,true);
		$criteria->compare('deleted',$this->deleted);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Levantamientos the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ClonesController.php
<?php

class ClonesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update', 'delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}


	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($id, $levid)
	{
		$model=new Clones;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		$subform = Subforms::model()->find("id = $id");
		$levantamiento = Levantamientos::model()->find("id = $levid");

		if(isset($_POST['Clones']))
		{
			
			$model->attributes=$_POST['Clones'];
			$model->subformid = $id;
			$model->idlev = $levid;
			$model->formid = $subform->megatree;
			$model->modified = date("Y-m-d H:i:s");
			if($model->save()){
				$registros = Respuestas::model()->findAll("subformid = $id AND levantamientoid = $levid");
				foreach ($registros as $registro){
					$nuevo = new Respuestas();
					$nuevo->attributes  = $registro->attributes;
					$nuevo->clonedid = $model->id;
					$nuevo->created = date("Y-m-d H:i:s");
					$nuevo->save();
				}
			
				$this->redirect(array('levantamientos/view','id'=>$levid));
			}
		}

		$this->render('create',array(
			'model'=>$model,
			'subform'=>$subform,
			'levantamiento' => $levantamiento,
		));
	}


	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$respuestas = Respuestas::model()->deleteAll(array("condition"=> "clonedid = $id"));
		
		$clone = $this->loadModel($id);
		$levantamientoid = $clone->idlev;
		$clone->delete();

		if(!isset($_GET['ajax']))
			$this->redirect(array('levantamientos/view','id'=>$levantamientoid));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Clones');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Clones('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Clones']))
			$model->attributes=$_GET['Clones'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Clones the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Clones::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Clones $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='clones-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/LevantamientosController.php
<?php

class LevantamientosController extends Controller
{

	function init()
	{
		parent::init();
		$app = Yii::app();
		if (isset(Yii::app()->user->lang))
		{
			$app->language = Yii::app()->user->lang;
		}

		Yii::app()->user->setState('mobile', true);
	}

	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
		array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index', 'view', 'create','update', 'delete', 'reports', 'editmode', 'exiteditmode'),
				'users'=>array('@'),
		),
		array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array(''),
				'roles'=>array("admin"),
		),
		array('deny',  // deny all users
				'users'=>array('*'),
		),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		Yii::app()->user->setState('levantamientoid', $id);
		$model = $this->loadModel($id);
		Yii::app()->user->returnUrl = $this->createUrl('levantamientos/index', array('companyid'=>$model->empresaid));
		//get forms
		$levantamientoarray = unserialize($model->formsactivos);
		$in = $levantamientoarray!=""?implode(",", $levantamientoarray):"0";
		$criteria = new CDbCriteria;  
		$criteria->addCondition('id IN ('.$in.')');
		$forms = Forms::model()->findAll($criteria);
		$company = Companies::model()->find("id=".Yii::app()->user->getState('companyid'));
		
		if(!$model->formsactivos){
			
			$this->render('error',array(
					'model'=>$model,
					'company' => $company,
			));
			
		}else{
			$data = array();
			$cloned = array();
			foreach ($forms as $form){
				$data[$form['id']] = Subforms::model()->findAll("megatree = ".$form['id']." AND released = 1 AND (deleted = 0 OR
						(deleted = 1 AND created < '$model->created' AND modified > '$model->created'))");
						$cloned[$form['id']] = Clones::model()->findAll("formid = ".$form['id']." AND idlev  = $model->id");
			}
			
			
			$this->render('view',array(
					'model'=>$model,
					'forms'=>$forms,
					'data' => $data,
					'company' => $company,
					'clones'=> $cloned,
			));
			
		}
		
		
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		Yii::app()->user->returnUrl = $this->createUrl('levantamientos/index', array('companyid'=>Yii::app()->user->getState('companyid')));
		$model=new Levantamientos;

		$forms = Forms::model()->findAll();
		$formsnames = array();
		foreach ($forms as $form){
			if($form['visible']==1 && $form['deleted']==0){
				$formsnames[$form['id']] = $form['name'];
			}
		}

		$users = Users::model()->findAll();
		$usersnames = array();
		foreach ($users as $user){
			$usersnames[$user['id']] = $user['email'];
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Levantamientos']))
		{
			$model->attributes=$_POST['Levantamientos'];
			 if($_POST['Levantamientos']['forms']!=='')
             	$model->formsactivos=serialize($_POST['Levantamientos']['forms']);//converting to string...
			
			$model->modified = date("Y-m-d H:i:s");
			$model->empresaid = Yii::app()->user->getState('companyid');
			
			if($model->save())
			$this->redirect(array('view','id'=>$model->id));
		}
		$company = Companies::model()->find("id=".Yii::app()->user->getState('companyid'));

		$this->render('create',array(
			'model'=>$model,
			'forms'=>$formsnames,
			'users' => $usersnames,
			'company' => $company,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		Yii::app()->user->returnUrl = $this->createUrl('levantamientos/index', array('companyid'=>$model->empresaid));
		
		
		$forms = Forms::model()->findAll();
		
		$formsnames = array();
		foreach ($forms as $form){
			if($form['visible']==1 && $form['deleted']==0){
				$formsnames[$form['id']] = $form['name'];
			}
		}

		$users = Users::model()->findAll();
		$usersnames = array();
		foreach ($users as $user){
			$usersnames[$user['id']] = $user['email'];
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Levantamientos']))
		{
			$model->attributes=$_POST['Levantamientos'];
			if($_POST['Levantamientos']['forms']!=='')
				$model->formsactivos = serialize($_POST['Levantamientos']['forms']);
			$model->modified = date("Y-m-d H:i:s");
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}
		$model->forms=unserialize($model->formsactivos);
		$company = Companies::model()->find("id=".Yii::app()->user->getState('companyid'));
		$this->render('update',array(
			'model'=>$model,
			'forms'=>$formsnames,
			'users' => $usersnames,
			'company' => $company,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model = $this->loadModel($id);
		$model->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
		$this->redirect(array('index', 'companyid'=>Yii::app()->user->getState('companyid')));
	}
	public function actionEditMode($id)
	{
		$model = $this->loadModel($id);

		Yii::app()->user->setState('editmode',1);
		$this->redirect(array('view', 'id'=>$id));
	}
	public function actionExitEditMode($id)
	{
		$model = $this->loadModel($id);

		Yii::app()->user->setState('editmode',0);
		$this->redirect(array('view', 'id'=>$id));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex($companyid)
	{
		Yii::app()->user->returnUrl = $this->createUrl('site/index');
		$dataProvider=new CActiveDataProvider('Levantamientos', array(
		    'criteria'=>array(
		        'condition'=>"empresaid= $companyid",
		        'order'=>'created DESC',
		),
		    'countCriteria'=>array(
		        'condition'=>"empresaid= $companyid",
		// 'order' and 'with' clauses have no meaning for the count query
		),
		    'pagination'=>array(
		        'pageSize'=>20,
		),
		));
		
		$company = Companies::model()->find("id=".$companyid);
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'company'=>$company,
		));
	}
	public function actionReports($id){
		$model=$this->loadModel($id);
		Yii::app()->user->returnUrl = $this->createUrl('levantamientos/'.$model->id);
		//get forms
		$levantamientoarray = unserialize($model->formsactivos);
		$in = "(".implode(",", $levantamientoarray).")";
		$criteria = new CDbCriteria;  
		$criteria->addCondition('id IN '.$in);
		$forms = Forms::model()->findAll($criteria);
		
		$this->render('reports',array(
			'model'=>$model,
			'forms'=>$forms,
		));
		
		
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Levantamientos the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Levantamientos::model()->findByPk($id);
		if($model===null)
		throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Levantamientos $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='levantamientos-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
}

protected/views/levantamientos/_view.php
<?php
/* @var $this LevantamientosController */
/* @var $data Levantamientos */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('titulo')); ?>:</b>
	<?php echo CHtml::encode($data->titulo); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('empresaid')); ?>:</b>
	<?php echo CHtml::encode($data->empresaid); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('info')); ?>:</b>
	<?php echo CHtml::encode($data->info); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('formsactivos')); ?>:</b>
	<?php echo CHtml::encode($data->formsactivos); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('conctadopor')); ?>:</b>
	<?php echo CHtml::encode($data->conctadopor); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('areacontacto')); ?>:</b>
	<?php echo CHtml::encode($data->areacontacto); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('completitud')); ?>:</b>
	<?php echo CHtml::encode($data->completitud); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('created')); ?>:</b>
	<?php echo CHtml::encode($data->created); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('modified')); ?>:</b>
	<?php echo CHtml::encode($data->modified); ?>
	<br /> <b><?php echo CHtml::encode($data->getAttributeLabel('deleted')); ?>:</b>
	<?php echo CHtml::encode($data->deleted); ?>
	<br />


</div>

protected/views/levantamientos/error.php
<?php

$this->setPageTitle($company['nombre']);
$this->breadcrumbs=array(
Yii::t('contentForm', 'recordlevantamientos')=>array('index', 'companyid'=>$model->empresaid),
$model->titulo,
);

?>
<h2>
<?php echo Yii::t('contentForm', 'recordlevantamientos');?>
</h2>

<p>No hay Propuestas Tipo seleccionados para este Levantamiento</p>
Seleccione Propuestas Tipo en <?php echo CHtml::link('Editar Levantamiento',array('levantamientos/update', 'id'=>$model->id)); ?>

<div class="row buttons">
	<?php echo CHtml::button("Volver", array("submit"=>$this->createUrl('levantamientos/index', array("companyid"=>$model->empresaid)), "data-ajax"=>"false")); ?>
	</div>

protected/views/levantamientos/view.php
<?php
/* @var $this LevantamientosController */
/* @var $model Levantamientos */
/*'forms'=>$forms,
			'data' => $data,
			'company' => $company,
			'clones'=> $cloned,*/
$this->setPageTitle($company['nombre']);
$this->breadcrumbs=array(
Yii::t('contentForm', 'recordlevantamientos')=>array('index', 'companyid'=>$model->empresaid),
$model->titulo,
);

?>

<?php if(Yii::app()->user->getState('editmode')!=1){?>
	<a href="<?php echo $this->createUrl('levantamientos/editmode', array('id'=>$model->id));?>" rel="external" data-mini="true" data-corners="true" data-wrapperels="span" style="float: right;" data-role="button" data-inline="true"><?php echo Yii::t('contentForm', 'editmode');?></a>
<?php }else{?>
	<a href="<?php echo $this->createUrl('levantamientos/exiteditmode', array('id'=>$model->id));?>" rel="external" data-mini="true" data-corners="true" data-wrapperels="span" style="float: right;" data-role="button" data-inline="true"><?php echo Yii::t('contentForm', 'exiteditmode');?></a>
	
<?php }?>

<h2><?php echo $model->titulo;?></h2>
	<div data-role="collapsible-set" data-theme="b" data-content-theme="d" >

		<?php foreach ($forms as $form){ ?>
			<?php $completitudform = array();?>
		<div data-role="collapsible" data-collapsed="true">
			<h2><?php echo $form->name?></h2> 
				<ul data-role="listview" data-theme="d"  data-divider-theme="d">
					<?php $subforms = $data[$form->id];?>
					<?php $cloned = $clones[$form->id];	?>
					<li data-role="list-divider"><?php echo Yii::t('contentForm', 'subforms');?><span class="ui-li-count"><?php echo count($subforms)+count($cloned);?></span></li>
					
					<?php 
					foreach ($subforms as $subform){
						if(MyUtils::checkSubForm($subform->id)){
							extract(MyUtils::getLastQuestionBySubform($subform->id, $model->id)); //$pregunta  $respuestas, $ultimavisita, $completitud, $idregistro
							//die(var_dump($completitud));
							if(Yii::app()->user->getState('editmode')==1){
								$url = "#popupMenu".$subform->id;
								$datarel = "data-rel = 'popup'";
							}else{
								$url = $this->createUrl('respuestas/index', array('subformid'=>$subform->id, 'levantamientoid'=>$model->id));
								$datarel = "rel='external'";
							}
					
						}else{
							$pregunta['name'] = Yii::t('contentForm', 'incompleteform');
							$ultimavisita = Yii::t('contentForm', 'never');
							$completitud = array();
							$completitud[] = 0;
							$url = "";
						}
						?>
											<li class="" data-idclone="0"  data-subform="4" data-levantamiento="3">
													<a href="<?php echo $url;?>" <?php echo $datarel;?> data-inline="true" data-transition="slideup" data-icon="gear" data-theme="e">
											    		<h3><?php echo $subform->name?></h3>
										                <p><strong><?php echo Yii::t('contentForm', 'lastvisit');?>: <?php echo $ultimavisita;?></strong></p>
										                <p><?php echo Yii::t('contentForm', 'nextquestion').": "; echo ($pregunta!=null)?($pregunta['name']):(Yii::t('contentForm', 'endreached'));?></p>
										                <p class="ui-li-aside"><strong>Completitud: <?php echo $completitud[0]."%"; echo isset($completitud[1])?" - ".$completitud[1]."%":"";?></strong></p>
									            	</a>
								            </li>
								            <?php if(Yii::app()->user->getState('editmode')==1){?>
								            	<div data-role="popup" id="popupMenu<?php echo $subform->id;?>" data-theme="d">
											        <ul data-role="listview" data-inset="true" style="min-width:210px;" data-theme="d"> 
											            <li><a rel="external" href="<?php echo $this->createUrl('respuestas/index', array('subformid'=>$subform->id, 'levantamientoid'=>$model->id));?>"><?php echo Yii::t('contentForm', 'gothrough');?></a></li>   
											            <li><a rel="external" href="<?php echo $this->createUrl('clones/create', array('id'=>$subform->id, 'levid'=>$model->id));?>"><?php echo Yii::t('contentForm', 'clonesubform');?></a></li>
											            <li><a rel="external" href="<?php echo $this->createUrl('respuestas/deleterespuestas', array('subformid'=>$subform->id, 'levantamientoid'=>$model->id));?>"><?php echo Yii::t('contentForm', 'deleteanswers');?></a></li>
											        </ul>
												</div>        
							            <?php }
							            
										$completitudform[] = isset($completitud[1])?round(($completitud[0]+$completitud[1])/2, 2):round($completitud[0], 2);
										
										}
					?>
		           
		            <?php 
		            	
		            	foreach ($cloned as $clon){
							if(MyUtils::checkSubForm($clon->subformid)){
								extract(MyUtils::getLastQuestionBySubform($clon->subformid, $clon->idlev, $clon->id)); //$pregunta  $respuestas, $ultimavisita, $completitud, $idregistro
								
								if(Yii::app()->user->getState('editmode')==1){
									$url = "#popupMenuClone".$clon->id;
									$datarel = "data-rel = 'popup'";
								}else{
									$url = $this->createUrl('respuestas/index', array('subformid'=>$clon->subformid, 'levantamientoid'=>$model->id,  'cloneid'=>$clon->id));      
									$datarel = "rel='external'";
								}
							
							}else{
								$pregunta['name'] = Yii::t('contentForm', 'incompleteform');
								$ultimavisita = Yii::t('contentForm', 'never');
								$completitud = array();
								$completitud[] = 0;
								$url = "";
							}
							?>
							<li class="" data-idclone="0"  data-subform="4" data-levantamiento="3">
									<a href="<?php echo $url;?>" <?php echo $datarel;?> data-inline="true" data-transition="slideup" data-icon="gear" data-theme="e">
							    		<h3><?php echo $clon->name?></h3>
						                <p><strong><?php echo Yii::t('contentForm', 'lastvisit');?>: <?php echo $ultimavisita;?></strong></p>
						                <p><?php echo Yii::t('contentForm', 'nextquestion').": "; echo ($pregunta!=null)?($pregunta['name']):(Yii::t('contentForm', 'endreached'));?></p>
						                <p class="ui-li-aside"><strong>Completitud: <?php echo $completitud[0]."%"; echo isset($completitud[1])?" - ".$completitud[1]."%":"";?></strong></p>
					            	</a>
				            </li>
				            <?php if(Yii::app()->user->getState('editmode')==1){?>
				            	<div data-role="popup" id="popupMenuClone<?php echo $clon->id;?>" data-theme="d">
							        <ul data-role="listview" data-inset="true" style="min-width:210px;" data-theme="d"> 
							            <li><a rel="external" href="<?php echo $this->createUrl('respuestas/index', array('subformid'=>$clon->subformid, 'levantamientoid'=>$model->id, 'cloneid'=>$clon->id));?>"><?php echo Yii::t('contentForm', 'gothrough');?></a></li>   				
										<li><?php echo  CHtml::link(CHtml::encode(Yii::t('contentForm', 'delete')), array('clones/delete', 'id'=>$clon->id),
										  array(
										    'submit'=>array('clones/delete', 'id'=>$clon->id),
										    'class' => 'delete','confirm'=>'¿Estás Seguro?'
										  )
										);?></li>
							            <li><a rel="external" href="<?php echo $this->createUrl('respuestas/deleterespuestas', array('subformid'=>$clon->subformid, 'levantamientoid'=>$model->id,  'cloneid'=>$clon->id));?>"><?php echo Yii::t('contentForm', 'deleteanswers');?></a></li>
							        </ul>
								</div>
			            
		            <?php }
		            	$completitudform[] = isset($completitud[1])?round(($completitud[0]+$completitud[1])/2, 2):round($completitud[0], 2);
		            	}?>
		            	
		            	<?php if(count($completitudform)>0){?>
		            		<li data-role="list-divider">Completitud del Formulario : <?php echo round(array_sum($completitudform)/count($completitudform), 2)."%";?></li>
						<?php }?>
				</ul>
		</div>
		<?php }?>
	
	</div>
	
	<div class="row buttons">
	<?php echo CHtml::button(Yii::t('contentForm', 'reports'), array("submit"=>$this->createUrl('levantamientos/reports', array("id"=>$model->id)), "data-ajax"=>"false")); ?>
	</div>